### ISSUE TITLE
[DevOps Roadmap] - HashiCorp Vault

### ISSUE THREAD

**Issue by mhmdio** [kamranahmedse/roadmap.sh#104]
#### What roadmap is this issue about?
- [X] DevOps Roadmap

#### What is this issue about?
- [X] Addition of a new item

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I suggest adding Hashicorp Vault as a new section or addition to IaC in the roadmap, its a security as a code tool. As a DevOps engineer, we use https://www.vaultproject.io/ multiple time, to manage the security aspect as a code, including policies, permissions, TLS, IAM, SSH, PKI etc.

**Comment by kiwivogel** [comment]
Having a separate security sub-group is a good idea in general. Ideally you'd have separate security engineers to handle this kind of stuff but for smaller shops you're invariably going to end up with a bunch of hats including security. Stuff like inspec/claire/openvas etc could also belong here but at the same time is are different beasts altogether. 

Something like this maybe: 

- Security:
1. IAM/secret management

- 1. Vault 
- 2. Active Directory
- 3. Etc.

2. Scanning/Auditing

- 1. Openvas/?
- 2. Claire/Anchore 
- 3. Inspec/?
