### ISSUE TITLE
[DevOps Roadmap] - Jenkins Location

### ISSUE THREAD

**Issue by bryandandan** [kamranahmedse/roadmap.sh#115]
Hi,

Is Jenkins in one of the three roadmaps?
If so can you help me locate it?

Many thanks

#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

**Comment by vallgorr** [comment]
Hi @bryandandan,

You can find Jenkins in [DevOps Roadmap](https://roadmap.sh/devops):

![image](https://user-images.githubusercontent.com/7808206/72996321-30a27a80-3e03-11ea-9123-a57a8e7dcd24.png)

**Comment by bryandandan** [comment]
Many thanks!
