### ISSUE TITLE
Create attachments for roadmap 'leaves'

### ISSUE THREAD

**Issue by akoikelov** [kamranahmedse/roadmap.sh#124]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hello! I guess that it'd be a good idea that roadmap trees were more interactive than just images. It would be great, that people could attach some useful links to posts or books, related to each leaf on the roadmap tree. Thanks

**Comment by kamranahmedse** [comment]
Hey, thank you for opening the issue. It is being worked upon and is planned to be added in the end of February release.
