### ISSUE TITLE
[DevOps Roadmap] - Dig command is duplicated in network category

### ISSUE THREAD

**Issue by HansUXdev** [kamranahmedse/roadmap.sh#137]
#### What roadmap is this issue about?
- [x ] DevOps Roadmap

#### What is this issue about?
- [x] Removal of some existing item

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.
