### ISSUE TITLE
link the relevant resources for each subject in roadmap

### ISSUE THREAD

**Issue by wangsmaster** [kamranahmedse/roadmap.sh#170]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X] All Roadmaps

#### What is this issue about?

- [X] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

It would be valuable to add highly-rated resources for each subject outlined in the roadmap. The resources could be online tutorials, or books for each subject. 
The benefit is that this functionality can make the roadmap more cohesive, as the users will be smoothly guided to a 'good' place to learn the subject of interests when they browse the roadmap.
