### ISSUE TITLE
Addition of a Data Science and Machine Learning roadmap

### ISSUE THREAD

**Issue by Ruth-ikegah** [kamranahmedse/roadmap.sh#173]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [+ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [+ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [+ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
Data is the new lingua franca of the tech world,  the world is moving to the age of creating sustainable machine learning models. A road map supporting those willing to start a career in data science or machine learning will be super helpful.

**Comment by SimitTomar** [comment]
Have created a Roadmap for Machine Learning, please refer to PR #189
