### ISSUE TITLE
[DevOps Roadmap] - Title should be DevOps Engineer Roadmap

### ISSUE THREAD

**Issue by rofrano** [kamranahmedse/roadmap.sh#174]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

The title should reflect that it is about the "DevOps Engineer" role and not about DevOps in general.

This chart is _heavily_ slanted towards Ops not DevOps (despite the title). DevOps is first and foremost about Culture. There is no reference to culture, or fast feedback, or lean thinking, or anything like that. Even the subtitle says: "Step by step guide for DevOps or any other Operations Role" By its own admission it views DevOps as an "Operations Role". DevOps is not an Ops Role. DevOps without Dev is just Ops!

That's a great chart on how to be a SysAdmin or "DevOps Engineer" but it is misleading because it doesn't include the entire Software Engineering side of DevOps (i.e., the Dev) This could also be a great chart for SRE (Site Reliability Engineer) as well but as it stands (even though it says it's "opinionated" and there is nothing wrong with that) it is proliferating the myth that DevOps is only about tools. I recommend changing the title to be more accurate. Thanks. 

~jr
