### ISSUE TITLE
[All Roadmaps] - Clarify "I wouldn't recommend" to clearly distinguish from "Order in roadmap not strict"

### ISSUE THREAD

**Issue by mharn** [kamranahmedse/roadmap.sh#180]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [x] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Usability: three of the four icons are circles with tick marks, but "I wouldn't recommend" is a grey circle with no tick. A grey circle with no tick doesn't appear anywhere on any roadmap - maybe grey circle should be changed to a grey square or rectangle. 
Also, "Order in roadmap not strict" shares the same grey colour - I also suggest changing this colour to more clearly differentiate the two.

**Comment by mjakubowski** [comment]
In addition or as an alternative to the suggestions above, add a definition of what the box colors mean.
Yellow - Mandatory(?)
Orange - Important(?)
Grey - I wouldn't recommend
White - Note
