### ISSUE TITLE
[DevOps Roadmap] - Linux OS selection 

### ISSUE THREAD

**Issue by am-mnandor** [kamranahmedse/roadmap.sh#182]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ x ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ x ] Addition of a new item
- [ ] Removal of some existing item
- [ x ] Changing in arrangement
- [ x ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ x ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I am not here to complain, I'm using linux 10 years by now.

It comes in so many different flavors and types, 

I would not omit Alpine and Arch linux.

Alpine is superior - not having musl. Lightweight, perfectly fine for the simpler cases.
Arch and Manjaro are all very nice and reliable tool for daily usage.

**Comment by chapmanjacobd** [comment]
NixOS is starting to be used in production at many companies
