### ISSUE TITLE
Roadmap graph/flowchart creation

### ISSUE THREAD

**Issue by mstellaris** [kamranahmedse/roadmap.sh#217]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

This is a generic question, about how you are creating the graphs for the roadmaps. 
Are you using a flowcharting application or simply some sort of image editing?
Apologies in advance for asking via a ticket.

**Comment by kamranahmedse** [comment]
Hey, it's [Balsamiq](https://balsamiq.com)

**Comment by mstellaris** [comment]
Thank you @kamranahmedse
