### ISSUE TITLE
[DevOps Roadmap] VCS, BS, DS

### ISSUE THREAD

**Issue by ybudimirov** [kamranahmedse/roadmap.sh#222]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

VCS systems: Git, Svn, etc
Branching strategies: gitflow, github flow, gitlab flow
Deployment strategies: rolling, blue/green, canary, etc
App build tools for java, node, ruby, go, etc

**Comment by iman4000** [comment]
i think there is need to have version control in road map and including these:
-git
-CVS
-Mercurial
-Monotone
-Bazaar
-TFS
and recommend these:
-git
-TFS
-CVS

**Comment by remyleone** [comment]
This is also a dependency for doing CI/CD with ease. It is going to be very difficult to understand CI/CD concepts if git methodology is not in place.
