### ISSUE TITLE
[Frontend Developer] - All roadmap sections : improvement thought.

### ISSUE THREAD

**Issue by PhantomHost** [kamranahmedse/roadmap.sh#227]
I've been learning to code on/off for the past 2 years and found your "roadmap" doc.  It is exactly the type of thing I was looking for.

The only thing that might make it easier to use is if you embed links into each section of the roadmap so that it is easy to follow- explore sections-return to the roadmap - Rinse, wash, repeat.  Does that make sense?

Thanks again for your work.  It's been very helpful.

Henry

#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

**Comment by cyrtified** [comment]
I totally agree; I love the roadmap, and links to the various resources would make it even better.
