### ISSUE TITLE
[DevOps Roadmap] - Typo in the Roadmap: initd

### ISSUE THREAD

**Issue by nguyenvulong** [kamranahmedse/roadmap.sh#229]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [X] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [X] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
Just a small typo: **intid** should be **initd**
![image](https://user-images.githubusercontent.com/1311412/104126901-8c626c80-53a2-11eb-89dd-1149f09e5009.png)

**Comment by aschaber1** [comment]
Probably a duplicate of #111.

**Comment by nguyenvulong** [comment]
> Probably a duplicate of #111.

indeed, it has been too long and i am not sure this repo is still maintained or not.
