### ISSUE TITLE
DevOps Roadmap: Node.js isn't a programming languaje

### ISSUE THREAD

**Issue by yunielrc** [kamranahmedse/roadmap.sh#231]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

**Comment by lacarone** [comment]
technically no but if you are only going to do backend "Node.JS (JavaScript)" could be a good replacement in this context, but probably we should think of other creative ways to indicate that you need to learn JavaScript but you can only use it in the context of NodeJS runtime (or alternative is Deno (created by the same guy)). Or even better use:

JavaScript  ------- NodeJS (recommended)
                  |------- Deno (alternative)
                  
same as indicated in this screenshot example: 
https://i.gyazo.com/56cc28dd76e6d2396491382f6cb95c17.png
