### ISSUE TITLE
Add Recoil as a state management library to the React Roadmap

### ISSUE THREAD

**Issue by thexpand** [kamranahmedse/roadmap.sh#252]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ x ] React Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ x ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ x ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I think that we should add Recoil to the State Management in addition to the other state management libraries. Not only it is a state management library, but it's developed by Facebook and was specifically built with React in mind. I've been using it in production applications for quite some time and to be honest - I don't miss Redux at all.
