### ISSUE TITLE
Add new item to Android developer roadmap

### ISSUE THREAD

**Issue by PuneetGopinath** [kamranahmedse/roadmap.sh#254]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

Not any of these, Android developer roadmap.

#### What is this issue about?

- [ ] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hi everyone!
I didn't check anything in the roadmap option above because the thing I wanted to discuss is about Android Developer roadmap. So, what I wanted to discuss is that I want to add `Learning basics of termux` in Android developer roadmap
Termux is a terminal for Android, almost same to Linux.
See also @termux
You can download PHP, git, GitHub official cli, ruby, nodejs, and many more.
I think if you want to become Android developer, the first to learn is termux!

Thanks in advance.
