### ISSUE TITLE
Word 'exhaustive' should be 'non-exhaustive' in the React roadmap

### ISSUE THREAD

**Issue by othomation** [kamranahmedse/roadmap.sh#255]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] React Roadmap
#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hello !

Just a little issue (I can make the PR if needed) in the React roadmap, at the presentation text.

It is written `Also, please note that the list below is exhaustive, and the items are listed in no particular order.`.
it should be `Also, please note that the list below is non-exhaustive, and the items are listed in no particular order. `
