### ISSUE TITLE
Frontend Roadmap :  [1] Addition of a new item [2] Removal of some existing item

### ISSUE THREAD

**Issue by Manik2375** [kamranahmedse/roadmap.sh#261]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hey! My name is Manik,

Ok, so lemme start..If anyone ask me the roadmap of frontend (I am only frontend) I give him link of this website, and he appreciate this resource.
So, I was looking at the resources in frontend roadmap, and It has _W3schools_ link.. Yeah, that's a good site.. but just for html. I'd not recommend it for css and js as most of its parts are outdated. That's why I opened this issue to remove them.

Instead You could add (https://developer.mozilla.org/) MDN for HTML , CSS & JS.  (https://javascript.info/)<-- this for JS, as a replacement of them. w3schools don't have a good reputation now due to their old resources..

Thankyou.

**Comment by pecampelo** [comment]
I don't know if i totally agree, it is in fact outdated in some portions but it is very readable for new users who have no idea what attributes are. I myself study and apply for positions in back-end, having studied it for 1 year and a half now, and I started meddling around with Dreamweaver when I was 17 by checking out W3 Schools and their tips.

I mean, MDN is pretty confusing sometimes if you don't know what you are looking for.

**Comment by Manik2375** [comment]
I agree with your arguments, 

Yeah sometime MDN can be confusing, andI have also used w3schools a lot. 
Well I think you are correct, for new users it can be very helpful specially for html. 

Well, I think I should close this issue (as I also used it in these days :P )

**Comment by pecampelo** [comment]
its nice to always chat with a fellow learner. cheers
