### ISSUE TITLE
[React Developer] - Roadmap for Russians

### ISSUE THREAD

**Issue by Ivan-Corporation** [kamranahmedse/roadmap.sh#292]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] React Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hi) i use your roadmap in my russian videos on YT (of course i give a link on your site) and i did some changes in React roadmap for russian speakers. Now i think that it would be honest if i suggest you my changed roadmap and maybe you will want to add this for russian speakers coming on your site (if you planing to do localisation of course ^) )
![react-roadmap](https://user-images.githubusercontent.com/58357980/131219595-47b46baa-e076-4848-bc07-467248b7f400.png)
