### ISSUE TITLE
[RequestRoadmap] - Desktop Developer Roadmap

### ISSUE THREAD

**Issue by jbduncan** [kamranahmedse/roadmap.sh#78]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

This is effectively a re-opening of https://github.com/kamranahmedse/developer-roadmap/issues/573.

Here are some things to consider including in the roadmap, as discussed in that issue:
- Frameworks such as Qt, GTK+, wxWidgets.
- Having sub-roadmaps for CLI and GUI.

**Comment by jbduncan** [comment]
@kamranahmedse By the way, I've noticed that the [contribution docs](https://github.com/kamranahmedse/roadmap.sh/contributing) seem to be missing, so the most I felt I could do was to read the [issue template](https://github.com/kamranahmedse/roadmap.sh/blob/master/.github/ISSUE_TEMPLATE.md).

Would you like me to raise a separate issue to address this? :)

**Comment by jbduncan** [comment]
Oops, never mind! I see that https://github.com/kamranahmedse/roadmap.sh/issues/76 already covers creating some contribution guidelines. ;)
